update_release_notes: fix rpm --checksig error handling
The rpm output for a valid rpm signature changed since SLE 11.

Instead of updating the grep pattern (and see it break again next year),
switch the check to use $?

Also log the full rpm output on error to make debugging easier.

diff --git a/salt/profile/documentation/files/update_release_notes b/salt/profile/documentation/files/update_release_notes
--- a/salt/profile/documentation/files/update_release_notes
+++ b/salt/profile/documentation/files/update_release_notes
@@ -276,8 +276,7 @@ while read line; do
                 test -f "$relrpm" || continue
                 RPM_NAME=$(rpm -qp --nosignature --nodigest --qf "%{NAME}" "$relrpm")
                 if [ "$RPM_NAME" = "$RELEASENOTES_NAME" ]; then
-                    CHECKED=$(rpm --checksig "$relrpm" | grep -vE "md5 gpg OK|pgp md5 OK")
-                    test -n "$CHECKED" && { echo "ERROR: $relrpm not signed" >&2 ; LOG "ERROR: $relrpm not signed"; continue ; }
+                    CHECKED=$(rpm --checksig "$relrpm") || { echo "ERROR: $relrpm not signed: $CHECKED" >&2 ; LOG "ERROR: $relrpm not signed: $CHECKED"; continue ; }
                     PRODUKT_ARCH=$arch
                     output_package "$relrpm" "$RELNOTESDIR/$arch/$PRODUKT_NAME/$PRODUKT_VERSION"
         #            create_index_file "$RELNOTESDIR/$BUILDMACHINETYPE/$PRODUKT_NAME"
